version: '3.9'
services:
  postgres:
    image: arshavirh/postgres-pgvector:1.2.0
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: kbase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
