server:
  port: 8080

spring:
  application:
    name: k_base
  datasource:
    url: jdbc:postgresql://localhost:5432/k_base
    username: postgres
    password: user123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        model: text-embedding-3-large
