server:
  port: 8080

spring:
  application:
    name: kbase
  datasource:
    url: jdbc:postgresql://localhost:5432/kbase
    username: postgres
    password: user123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    vector-store:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000
        schema-validation: true
        schema-name: public
        table-name: vector_store
    openai:
      api-key: ${OPENAI_API_KEY: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}
      embedding:
        options:
          model: text-embedding-3-small

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

mcp:
  knowledge:
    docs-path: /Users/arshavirhunanyan/projects/personal/k_base/docs
