server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  application:
    name: kbase
  datasource:
    url: jdbc:postgresql://localhost:5432/kbase
    username: postgres
    password: user123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    vector-store:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000
        schema-validation: true
        schema-name: public
        table-name: vector_store
    mcp:
      server:
        name: kbase-mcp
        version: 0.0.1
        type: SYNC
        stdio: true
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        enabled: true
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small


management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
  tracing:
    enabled: false
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
  metrics.distribution.percentiles-histogram.http.server.requests: true
  endpoints.web.exposure.include: health,info,env,configprops,metrics,custom

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

mcp:
  knowledge:
    docs-path: /Users/arshavirhunanyan/projects/personal/k_base/docs

logging:
  level:
    root: INFO
    com.buildware.kbase: INFO
